# Generated by Django 5.0.7 on 2024-07-17 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='baga',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
